### ISSUE TITLE
Enhancement: Add Loading Spinner During API Requests

### ISSUE THREAD

**Issue by FaheemOnHub** [FaheemOnHub/IP-Address-Location-Tracker#5]
Description:
Improve user experience by adding a loading spinner or indicator while waiting for API requests to complete. This will provide visual feedback to users, indicating that the application is actively fetching data.

Skills Required:

    HTML/CSS for spinner implementation
    JavaScript for dynamic loading behavior

**Comment by anishyadavv** [comment]
can i work on this issue

**Comment by FaheemOnHub** [comment]
> can i work on this issue

Already solved by @PG-257811 .
There are other issues also , you can give work on them.
