### ISSUE TITLE
[BUG] Previous markers on the map are still visible after a new IP search.

### ISSUE THREAD

**Issue by RuthwikReddy09** [FaheemOnHub/IP-Address-Location-Tracker#8]
Previously searched IP address markers are visible on map even after entering a new IP address.

[screen-capture.webm](https://github.com/FaheemOnHub/IP-Address-Location-Tracker/assets/126862059/cd49e981-f808-4118-bb25-195c4c93d48e)

**Comment by LyubomirT** [comment]
I think I can work on this. Please assign the issue to me?

**Comment by LyubomirT** [comment]
@RuthwikReddy09 @FaheemOnHub Fixed the issue. Please take a look at #10 and let me know if you have any questions or if you want to change something.

**Comment by FaheemOnHub** [comment]
The bug has been resolved by @LyubomirT
